import type { NodeTypes } from '@xyflow/react';
import {
  StartNode,
  EndNode,
  MenuNode,
  PlayMessageNode,
  CollectDigitsNode,
  QueueNode,
  AgentDirectNode,
  BusinessHoursNode,
  TransferNode,
  VoicemailNode,
  BranchNode,
  HttpRequestNode,
  CallbackNode,
  SetVariableNode,
  HuntGroupNode,
  SubAutoAttendantNode,
  RepeatMenuNode,
} from './AllNodes';

export const nodeTypes: NodeTypes = {
  start: StartNode,
  end: EndNode,
  menu: MenuNode,
  playMessage: PlayMessageNode,
  collectDigits: CollectDigitsNode,
  queue: QueueNode,
  agentDirect: AgentDirectNode,
  huntGroup: HuntGroupNode,
  subAutoAttendant: SubAutoAttendantNode,
  repeatMenu: RepeatMenuNode,
  businessHours: BusinessHoursNode,
  transfer: TransferNode,
  voicemail: VoicemailNode,
  branch: BranchNode,
  httpRequest: HttpRequestNode,
  callback: CallbackNode,
  setVariable: SetVariableNode,
};
